version: '3.9'
services:
  dfssvm_645e3a0099db361fdab687ca:
    container_name: dfssvm_645e3a0099db361fdab687ca
    build:
      context: .
    ports:
    - 6000:6005/tcp
    tty: true
    volumes:
    - type: tmpfs
      target: /target
      tmpfs:
        size: 1G
    - type: volume
      source: dfssvm_645e3a0099db361fdab687ca
      target: /dfssvm_645e3a0099db361fdab687ca
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities:
            - gpu
volumes:
  dfssvm_645e3a0099db361fdab687ca: {}
