version: '3.9'
services:
  fjasldf_644ece15809917bf2dc3956c:
    container_name: fjasldf_644ece15809917bf2dc3956c
    build:
      context: .
    ports:
    - 9000:9000/tcp
    - 9080:980/udp
    tty: true
    volumes:
    - type: tmpfs
      target: /target
      tmpfs:
        size: 1G
    - type: volume
      source: fjasldf_644ece15809917bf2dc3956c
      target: /fjasldf_644ece15809917bf2dc3956c
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities:
            - gpu
volumes:
  fjasldf_644ece15809917bf2dc3956c: {}
